Resources:
  CourseOrganizerQueue:
    Type: AWS::SQS::Queue
    ReceiveMessageWaitTimeSeconds: 20
    Properties:
      QueueName: ${self:custom.queueName}

Outputs: 
  QueueURL: 
    Description: "URL of SQS Queue"
    Value: 
      Ref: CourseOrganizerQueue