Resources:
  CourseOrganizerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.queueName}
      ReceiveMessageWaitTimeSeconds: 20

Outputs: 
  QueueURL: 
    Description: "URL of SQS Queue"
    Value: 
      Ref: CourseOrganizerQueue